version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"

  siteblog:
    image: ${DOCKER_REGISTRY-}siteblog
    build:
      context: .
      dockerfile: SiteBlog/Dockerfile
    depends_on:
      - db
