version: '3.4'

services:
  db:
    environment:
      SA_PASSWORD: "blog@2022"
      ACCEPT_EULA: "Y"
    ports:
      - "14331:1433"

  siteblog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro